### ISSUE TITLE
NoSuchMethodError Exception using IntelliJ IDEA 2023.3.3  

### ISSUE THREAD

**Issue by sigma-sappel** [redhat-developer/intellij-redhat-telemetry#80] opened 2024-02-09 08:18 UTC
Reproduce:
- Install IntelliJ IDEA 2023.3.3
- Install the Redhat Dependency Analytics Plugin 0.9.0.105
- Configure Path to Maven and Java
-  Open Maven project and open pom.xml

-> IDE catches Exception

```
java.lang.NoSuchMethodError: 'com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.property(java.lang.String, java.lang.String)'
	at org.jboss.tools.intellij.exhort.ApiService.getComponentAnalysis(ApiService.java:82)
	at org.jboss.tools.intellij.componentanalysis.CAService.performAnalysis(CAService.java:64)
	at org.jboss.tools.intellij.componentanalysis.CAAnnotator.lambda$doAnnotate$1(CAAnnotator.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by adietish** [comment] 2024-05-17 09:11
Hi @sigma-sappel, sorry for the late reply and thanks for reporting it.

I was aware of this and afaik had fixed this in https://github.com/redhat-developer/intellij-openshift-connector/issues/651 back when it was discovered. It was caused by the release of telemetry 1.1.0 while having telemetry 1.0.0 present in IDEA still.

**Comment by adietish** [comment] 2024-05-17 09:12
Afaik this was fixed, Closing.

@sigma-sappel: feel free to repoen if you still experience it.

**Closed by adietish** 2024-05-17 09:12 UTC
